SGX Wallet Documentation
skalenetwork/documentation pull request #11
Opened 2020-04-06 17:36 UTC by ebruoguzberk

2020-04-09 19:02 UTC, christineRPM submitted a review, later dismissed
looks good

2020-04-10 11:12 UTC, cstrangedk commented on validators/sgx-wallet.md
> +**Instal SGX Library:**
typo -> Install

2020-04-10 11:14 UTC, cstrangedk commented on validators/sgx-wallet.md
> +Note: if you are not using Ubuntu 18.04 (something that we do not recommend), you may need to rebuild the sgx-software-enable utility before use by typing:
replace we

2020-04-10 11:23 UTC, cstrangedk commented on validators/sgx-wallet.md
> +Set SGX in BIOS as enabled (preferrably) or software-controlled.
typo -> preferably

2020-04-10 11:34 UTC, cstrangedk requested changes
small fixes needed

2020-04-10 20:48 UTC, ebruoguzberk commented on validators/sgx-wallet.md
> +**Instal SGX Library:**
done

2020-04-10 20:49 UTC, ebruoguzberk commented on validators/sgx-wallet.md
> +Note: if you are not using Ubuntu 18.04 (something that we do not recommend), you may need to rebuild the sgx-software-enable utility before use by typing:
changed

2020-04-10 20:49 UTC, ebruoguzberk commented on validators/sgx-wallet.md
> +Set SGX in BIOS as enabled (preferrably) or software-controlled.
changed

2020-04-11 09:56 UTC, cstrangedk submitted a review, later dismissed
lgtm, thank you! 🚀

2020-04-15 17:30 UTC, cstrangedk approved these changes

2020-04-15 17:35 UTC, christineRPM approved these changes
Looks good

2020-04-15 17:36 UTC, merged