2.0.0 Testnet documentation
skalenetwork/documentation pull request #155
Opened 2021-07-12 12:08 UTC by badrogger

2021-07-12 16:53 UTC, dmitry-tk requested changes

2021-07-12 16:53 UTC, dmitry-tk commented on validators/fuji/fuji-versions.md
> +MANAGER_CONTRACTS_ABI_URL=https://github.com/skalenetwork/skale-network/blob/master/releases/rinkeby/skale-manager/1.8.1/skale-manager-1.8.1-beta.1-rinkeby-abi.json
Wrong link, change to raw

2021-07-12 16:53 UTC, dmitry-tk commented on validators/fuji/soft-upgrade-testnet.md
> +MANAGER_CONTRACTS_ABI_URL=https://github.com/skalenetwork/skale-network/blob/master/releases/rinkeby/skale-manager/1.8.1/skale-manager-1.8.1-beta.1-rinkeby-abi.json
same here

2021-07-12 17:09 UTC, badrogger commented on validators/fuji/soft-upgrade-testnet.md
> +MANAGER_CONTRACTS_ABI_URL=https://github.com/skalenetwork/skale-network/blob/master/releases/rinkeby/skale-manager/1.8.1/skale-manager-1.8.1-beta.1-rinkeby-abi.json
addressed

2021-07-12 17:09 UTC, badrogger commented on validators/fuji/fuji-versions.md
> +MANAGER_CONTRACTS_ABI_URL=https://github.com/skalenetwork/skale-network/blob/master/releases/rinkeby/skale-manager/1.8.1/skale-manager-1.8.1-beta.1-rinkeby-abi.json
addressed

2021-07-12 21:57 UTC, ebruoguzberk commented
I didn't check the version numbers but the documentation looks good.

2021-07-12 21:57 UTC, ebruoguzberk commented
Please review and push this tomorrow for Fabio

2021-07-12 21:57 UTC, ebruoguzberk approved these changes

2021-07-13 04:42 UTC, cstrangedk approved these changes

2021-07-13 04:42 UTC, merged