New validator node version - back up - token economics
skalenetwork/documentation pull request #24
Opened 2020-07-25 03:10 UTC by ebruoguzberk

2020-07-25 09:34 UTC, cstrangedk requested changes
pull backup.md directly from the sgxwallet repo instead of duplicating here

2020-07-27 14:31 UTC, cstrangedk requested changes

2020-07-27 15:30 UTC, cstrangedk approved these changes

2020-07-27 17:57 UTC, christineRPM approved these changes
approved

2020-07-27 17:58 UTC, merged